name: Deploy Frontend to EC2

on:
  push:
    branches: [ "main" ] # Cambiar a "principal" si tu rama por defecto se llama así

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Instalar dependencias
      run: npm ci # Usa 'npm ci' en entornos de CI para instalaciones limpias y exactas

    - name: Compilar proyecto (Build)
      run: npm run build

    - name: Copiar archivos a la EC2 (Nginx)
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "dist/*"
        target: "/usr/share/nginx/html/"
        strip_components: 1 # Evita que se cree la carpeta 'dist/' dentro de la ruta de Nginx
